### ISSUE TITLE
Opam package on opam.ocaml.org?

### ISSUE THREAD

**Issue by smondet** [whitequark/ppx_getenv#2]
Is there any reason this one has not been submitted to opam?

(Not that I definitiely want to use it, just exploring options)

**Comment by whitequark** [comment]
Not sure what the point is. Is it useful for you?

**Comment by smondet** [comment]
I was just evaluating options, there is `ppx_blob` already (→ which means having to deal with paths instead of environment variables).

**Comment by whitequark** [comment]
Oh, if you actually want to use it, sure, I'll upload
It was meant as an example you know

**Comment by smondet** [comment]
If you have time, yes upload please :)

**Comment by whitequark** [comment]
https://github.com/ocaml/opam-repository/pull/3879
